module.exports = {
  apps: [
    {
      name: "pricepick-cms-dev-6001",
      script: "node_modules/.bin/next",
      args: "start -p 6001",
      cwd: "/home/sindykorea/pricepick/pricepick-cms-dev",
      exec_mode: "cluster",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: { NODE_ENV: "production" },
    },
    {
      name: "pricepick-cms-stg-6002",
      script: "node_modules/.bin/next",
      args: "start -p 6002",
      cwd: "/home/sindykorea/pricepick/pricepick-cms-stg",
      exec_mode: "cluster",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: { NODE_ENV: "production" },
    },
    {
      name: "pricepick-cms-6003",
      script: "node_modules/.bin/next",
      args: "start -p 6003",
      cwd: "/home/sindykorea/pricepick/pricepick-cms-prod",
      exec_mode: "cluster",
      instances: 4,
      autorestart: true,
      watch: false,
      max_memory_restart: "2G",
      env: { NODE_ENV: "production" },
    },
  ],
};